version: 2
updates:
  - package-ecosystem: github-actions
    directory: ".github/workflows/"
    schedule:
      interval: "daily"
    labels:
      - "github"
      - ":arrow_up: dependency"
  - package-ecosystem: "gomod"
    directory: "backend/"
    schedule:
      interval: "daily"
    labels:
      - ":computer: backend"
      - ":arrow_up: dependency"
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
    labels:
      - ":spider_web:  frontend"
      - ":arrow_up: dependency"
  - package-ecosystem: docker
    directory: "frontend/"
    schedule:
      interval: "daily"
    labels:
      - ":whale: docker"
      - ":arrow_up: dependency"
  - package-ecosystem: docker
    directory: "docker/postgres/"
    schedule:
      interval: "daily"
    labels:
      - ":whale: docker"
      - ":arrow_up: dependency"
