services:
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    container_name: mt-dev-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mt_dev
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: mt-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/data

volumes:
  dev-postgres-data:
  dev-redis-data:
